version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend_cpp
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
      - ./models:/app/models
    environment:
      - DB_HOST=mongodb
      - TOR_ENABLED=true

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080

volumes:
  mongodb_data:
